### PR TITLE
Develop localize

### PR DESCRIPTION
**Pull request by mgage**
Replace more occurrences of dueDate with closeDate including variables $dueDate to $closeDate for example.  Risky but so far I haven't gotten any errors.

A few minor updates on maketext phrases including one for the footer in ContentGenerator.pm

There are some more maketext phrase updates to come.

### CODE REVIEW

**Comment by goehle** [comment]
Are you sure you want to change dueDate to closeDate in the code itself (and not just how it is displayed to the user)?  One of the benefits of changing just the verbage "due date" to "close date" (as opposed to reordering the due date and reduced credit date) was that it wouldn't introduce any bugs.  Changing the variables names in the code opens up a can of worms in that all of the functionality needs to be rechecked.

**Comment by mgage** [comment]
Caught one error with reading old .def files.  Now accepts dueDate as well as closeDate in those files.

due_date is still due_date.  Changing that starts to mess with the database which is a little too scary. So due_date means close_date.  There are a few configuration parameters which I might consider changing once things settle down -- for example:  check_answers_after_due_date

**Comment by goehle** [comment]
I think if we are going to start messing around with code then we should
leave due date as due date and reorder due date and reduced credit date.
Changing due date to close date in the code introduces bugs (you just found
one) and is incomplete because the database field and accessors are all
still due date.  So now you have

```
$set->due_date($closeDate)
```

and I don't know that that reduces coder confusion.  I'll pull this if you
really feel strongly about the change, but its just setting us up for more
work.

**Comment by mgage** [comment]
I don’t feel that strongly.  In any case I wouldn’t pull this immediately since as you point out there is still a risk
that there are outstanding errors — most likely compatibility with old installations — that I haven’t found yet.

I can submit this later directly to develop at a later date if it seems desirable then. There are few changes
besides the dueDate to closeDate change.    While it’s true there is 
a chance of introducing bugs I’d rather deal with them soon while I’m familiar with the code than later when
I’ve forgotten.

  I’m not sure what you mean by “leave due date as due date and reorder due date and reduced credit date”.  I thought it was a good idea to indicate a completely new term (closeDate) to avoid confusion.  Did you want to rename these?

**Comment by goehle** [comment]
The intention behind changing the phrase "due date" to "close date" was because people intuitively feel that the "reduced credit date" should be _after_ the "due date".  Changing the phrase "due date" to "close date" is a compromise at making the role of that field clearer (it really is a close date) without changing how reduced credit works.  The other option would be to actually change the order of due date and the reduced credit date so that the due date comes first.  If reduced credit is enabled then after the due date the set would be open with reduced credit until the reduced credit date.  If reduced credit is not enabled then after the due date the set would close.  This is, I think, how people intuitively expect it to behave.

**Comment by mgage** [comment]
I don’t feel strongly about this and I haven’t invested all that much time in tracking down the occurrences of dueDate.

I’ll leave it up to you as to whether to pull this or ignore it — especially if you feel strongly about it.

**Comment by goehle** [comment]
Hmm.  Why don't you separate this out as a separate pull request to openwebwork.  The only reason the close date stuff is included in the localization pull is that I was revamping the pot file anyway, so it made sense to get the "close date" terminology in there so that translation is easier.

**Comment by mgage** [comment]
I'll withdraw this for now.

**Comment by mgage** [comment]
OK.  That’s done.  I’m pretty sure I found all the changes I made other than dueDate to closeDate.

We can let that sit until we’re bored.

Take care,

Mike

**Pull request closed without merging**
